### ISSUE TITLE
Chapitre 9.2 : build.sh non fonctionnel

### ISSUE THREAD

**Issue by dbillon** [dunod-docker/docker-examples-edition2#1]
Apres le lancement de "docker-examples-edition2/chapitre9/supervisor/build.sh", une erreur ne permet pas d'initialiser la base ... le conteneur n'est pas créé :

> Step 4/21 : RUN /usr/bin/mysql_install_db --user=mysql     && chown -R mysql:mysql /var/lib/mysql
>  ---> Running in 66be9a0ea76d
> Neither host '66be9a0ea76d' nor 'localhost' could be looked up with
> '/usr/libexec/resolveip'
> Please configure the 'hostname' command to return a correct
> hostname.
> If you want to solve this at a later stage, restart this script
> with the --force option
> 
> The latest information about mysql_install_db is available at
> https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
> The command '/bin/sh -c /usr/bin/mysql_install_db --user=mysql     && chown -R mysql:mysql /var/lib/mysql' returned a non-zero code: 1
> 

Cette erreur est à priori un bug de la version MariaDB. Il faut ajouter --force dans la commande issue de "docker-examples-edition2/chapitre9/supervisor/Dockerfile" :

> RUN /usr/bin/mysql_install_db --user=mysql **--force** \
>     && chown -R mysql:mysql /var/lib/mysql
>

**Comment by tgarlot** [comment]
J'ai regardé le problème et je confirme que l'option --force corrige le problème.
