### ISSUE TITLE
chmod: gradlew: No such file or directory

### ISSUE THREAD

**Issue by dim-ops** [dunod-docker/docker-examples-edition2#10]
Hello,

My Jenkin's job fails, I obtain the message "chmod: gradlew: No such file or directory". I see in the book's picture that gradle-4.8.1.bin.zip has to be download but I don't find a solution.

![image](https://user-images.githubusercontent.com/36767102/82375362-c56b5c80-9a20-11ea-83a6-a17b3829a696.png)
Thank you.

**Comment by tgarlot** [comment]
Hi,
I had a look at the error and I don't see what is going wrong. The `chmod` command is run in the appex-build-java image. If you `docker image ls`, do you see this image? How does the build folder looks like once the job has failed (remove the script that cleans everything to keep the folder)? Is the appex-front-end repository properly cloned?

**Comment by tgarlot** [comment]
Closing as no feedback.
