### ISSUE TITLE
Impossible de lancer le daemon docker sur AKS

### ISSUE THREAD

**Issue by rgeromegnace** [dunod-docker/docker-examples-edition2#11]
Bonjour

Lors de ma lecture du chapitre 12 j'ai constaté qu'il m'était impossible de traiter les exemples sur AKS.
Dès que je lance le script build.sh j'ai une erreur me disant que le daemon docker n'est pas lancé.
En cherchant un peu sur le web il est dit que kubernetes utilisait désormais containerd. Quel est l'impact?

Comment faire pour tester les exemples sur mon instnace AKS.

**Comment by tgarlot** [comment]
Bonjour,

La commande build.sh doit être tournée localement (sur votre PC) et non pas sur l'AKS. Si vous obtenez une information que le daemon docker n'est pas lancé, il faut regarder si Docker Desktop (ou directement le démon) tourne bien.

Pour vérifier si l'AKS est disponible, il suffit normalement de lancer une commande `kubectl get nodes` par exempl: si vous obtenez la liste des noeuds, c'est que tout est en ordre.

**Comment by rgeromegnace** [comment]
Bonjour,

Effectivement c'était bien ça.

Merci, je peux finir ma lecture de ce livre passionnant.
