### ISSUE TITLE
Chapitres 9.3 / 9.4 : plantage front-end 

### ISSUE THREAD

**Issue by dbillon** [dunod-docker/docker-examples-edition2#2]
Le container front-end fonctionne correctement au début : page login/password et chargement de données CSV.
Par contre, il plante lors de la visualisation 

> Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> Fri Dec 13 17:33:45 GMT 2019
> There was an unexpected error (type=Internal Server Error, status=500).
> Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

A priori le programme Java n'arrive pas à communiquer avec mysql sur le conteneur appex-db 

> 2019-12-13 17:21:15.842 ERROR 1 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Tout les contrôles de base semblent pourtant corrects 

- conteneur appex-db lancé
- accès à mysql possible depuis l'hôte
- pas de problème visible dans le fichier /config/application.properties de appex-front-end

**Comment by tgarlot** [comment]
J'avoue ne pas réussir à reproduire le problème... Si vous relancez la commande `./run.sh`, avez-vous encore le problème?

**Comment by tgarlot** [comment]
No feedback... je ferme.
