### ISSUE TITLE
Chapitre 10 : version Jenkins...

### ISSUE THREAD

**Issue by dbillon** [dunod-docker/docker-examples-edition2#3]
La version Jenkins forcée dans le Dockerfile ne permet plus de charger ensuite les plugins par défaut (affichage de nombreuses erreurs au chargement).
Changement effectué dans "chapitre10/jenkins/Dockerfile" pour charger la dernière version de Jenkins : FROM jenkins/jenkins
A date version 2.209 utilisée au lieu de la 2.143 imposée dans le Dockerfile initial
Le T.P. fonctionne bien avec cette version. Plus de problème de chargement des plugins.

**Comment by tgarlot** [comment]
je confirme que la version 2.143 ne démarre plus... Mise à jour de la version à 2.210 (dernière version) fonctionne bien.
