### ISSUE TITLE
utilisation de socat (page 63)

### ISSUE THREAD

**Issue by herrib** [dunod-docker/docker-examples-edition2#4]
L'instruction: _socat -v UNIX-LISTEN:/tmp/socatproxy.sock, fork, reuseaddr UNIX-CONNECT:/var/run/docker.sock &_
renvoie un message d'erreur (exactly 2 addresses required (there are 4).

_socat -v UNIX-LISTEN:/tmp/socatproxy.sock, UNIX-CONNECT:/var/run/docker.sock &_ initialise correctement le process et la commande _docker -H unix:///tmp/socatproxy.sock ps -a_ aboutit au résultat attendu.

La version socat suit:

socat version 1.7.3.2 on May 14 2019 05:11:55
   running on Linux version #1 SMP Wed Dec 4 17:04:30 UTC 2019, release 4.18.0-151.el8.x86_64, machine x86_64

Le host est sous Linux Centos8 4.18.0-151.el8.x86_64

**Comment by tgarlot** [comment]
Je reproduis le problème en utilisant directement Docker Desktop sous mac. Par contre la commande marche correctement sous Linux (via VirtualBox donc pas un Linux natif). 
La commande alternative ci-dessus fonctionne dans les 2 cas

**Comment by tgarlot** [comment]
Corrigé + erratum sur le site web
