### ISSUE TITLE
utilisation de brctl (pages 183 et suivantes)

### ISSUE THREAD

**Issue by herrib** [dunod-docker/docker-examples-edition2#5]
bridge-utils ne fait plus partie des packages des versions RedHat 7.7 et supérieures (idem donc pour Centos). brctl n'est donc plus disponible et il faut utiliser ip et ses diverses options .

**Comment by tgarlot** [comment]
Merci pour le commentaire. Erratum ajouté sur https://dunod-docker.github.io/post/erratum-edition-2/
