### ISSUE TITLE
9.3.1 initialisation de la database

### ISSUE THREAD

**Issue by herrib** [dunod-docker/docker-examples-edition2#7]
Le script  docker-examples-edition2/chapitre9/multi-conteneurs/run.sh contient la commande suivante:

# Initialisation de la base de données
docker exec appex-db /bin/bash -c "/usr/bin/mysql -v -u root -p${MYSQL_ROOT_PASSWORD} < /schema.sql"

Il semble que la commande échoue.

Le front end ne peut dès lors accéder à la base:

Thu Jan 02 17:37:33 GMT 2020
There was an unexpected error (type=Internal Server Error, status=500).
Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'insee_data'

Environnement: VM Ubuntu 18.04-1

**Comment by tgarlot** [comment]
Le problème vient surement du fait que la base de données n'a pas eu le temps de démarrer AVANT que la commande `docker exec appex-db /bin/bash -c "/usr/bin/mysql -v -u root -p${MYSQL_ROOT_PASSWORD} < /schema.sql"` ne soit lancée.

Il y a un `sleep 20` qui laisse normalement le temps à mariadb de démarrer avant de créer le schéma. 
Si tout se passe bien, le script affiche:

```
--------------
CREATE SCHEMA IF NOT EXISTS `insee_data` DEFAULT CHARACTER SET utf8
--------------

--------------
CREATE TABLE IF NOT EXISTS `insee_data`.`departement` (
  `code` VARCHAR(3) NOT NULL,
  `population` INT NOT NULL,
  `nombre_hotel` INT NOT NULL,
  `commune_plus_grande` VARCHAR(255) NOT NULL,
  `commune_plus_petite` VARCHAR(255) NOT NULL,
  `last_update` DATETIME NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
--------------
```

Sinon on obtient un:
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")`

Si cela est un problème récurrent sur votre configuration matérielle, il suffit d'augmenter le `sleep` à 30 ou 40 secondes. Dans le chapitre sur Docker Compose, on utilise un scirpt wait-for-it.sh qui permet de prévenir ce problème en s'assurant que mariaDB est prête AVANT de lancer la création du schéma
