### ISSUE TITLE
Chapitre 10 : Erreur scripts Jenkins

### ISSUE THREAD

**Issue by louis-h** [dunod-docker/docker-examples-edition2#9]
Bonjour , j'ai remarqué une erreur dans le CI_BUILD_DEV Jenkins (10.4 page 237)

/opt/build/scripts/start-build.sh ${BUILD_TAG} 
/opt/build/scripts/build-java.sh ${BUILD_TAG} 
/opt/build/scripts/build-configure.sh ${BUILD_TAG} “DEV”
/opt/build/scripts/build-front-end-image.sh ${BUILD_TAG} 

le script build-configure.sh se plante à cause des guillemets du paramètre "DEV" 

### ```
_BUILD SUCCESSFUL in 19m 21s
4 actionable tasks: 3 executed, 1 up-to-date
+ /opt/build/scripts/build-configure.sh jenkins-CI_BUILD_DEV-1 “DEV”
Cloning into 'appex-front-end-configuration'...
cp: cannot stat 'appex-front-end-configuration/“DEV”_application.properties': No such file or directory
Build step 'Execute shell' marked build as failure
[PostBuildScript] - [INFO] Executing post build scripts.
[PostBuildScript] - [INFO] Executing the script /opt/build/scripts/end-build.sh with parameters [jenkins-CI_BUILD_DEV-1].
[CI_BUILD_DEV] $ /bin/bash /tmp/jenkins7691694063878636332.sh jenkins-CI_BUILD_DEV-1
*********** Destruction du répertoire de build jenkins-CI_BUILD_DEV-1 ***********
Finished: FAILURE_

```
Il faut enlever les guillemets et ça fonctionne mieux
Sinon Bravo pour ce livre et les tutos qui sont excellents
Louis

**Comment by tgarlot** [comment]
Je pense que le soucis ne viens pas du script directement (je l'ai retesté et les guillemets sont acceptés). Par contre, si vous avez copié DIRECTEMENT le contenu du texte depuis le README.md de ce dépot, le format des guillemets est effectivement incorrect. Je corrige cela

**Comment by tgarlot** [comment]
Fixe dans commit https://github.com/dunod-docker/docker-examples-edition2/commit/cb69432de5c68cae1919504f14045110cf76d569
